-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 21:04:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(250) NOT NULL,
  `user_name` VARCHAR(250) NOT NULL,
  `user_password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` INT(9) NOT NULL,
  `usuarios_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `usuarios_user_id`),
  INDEX `fk_Cliente_usuarios1_idx` (`usuarios_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_usuarios1`
    FOREIGN KEY (`usuarios_user_id`)
    REFERENCES `mydb`.`usuarios` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`arquivo` (
  `id` INT(11) NOT NULL,
  `titulo` VARCHAR(250) NOT NULL,
  `comentario` TEXT(250) NOT NULL,
  `usuarios_user_id` INT(11) NOT NULL,
  `Cliente_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `usuarios_user_id`, `Cliente_id`),
  INDEX `fk_arquivo_usuarios_idx` (`usuarios_user_id` ASC) VISIBLE,
  INDEX `fk_arquivo_Cliente1_idx` (`Cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_arquivo_usuarios`
    FOREIGN KEY (`usuarios_user_id`)
    REFERENCES `mydb`.`usuarios` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arquivo_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `mydb`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
