-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 15:34:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(255) NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`),
  INDEX `fk_clientes_usuarios_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_clientes_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`tipo` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`arquivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `data` DATE NOT NULL,
  `clientes_id` INT NOT NULL,
  `clientes_usuarios_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `clientes_id`, `clientes_usuarios_id`, `tipo_id`),
  INDEX `fk_arquivos_clientes1_idx` (`clientes_id` ASC, `clientes_usuarios_id` ASC),
  INDEX `fk_arquivos_tipo1_idx` (`tipo_id` ASC),
  CONSTRAINT `fk_arquivos_clientes1`
    FOREIGN KEY (`clientes_id` , `clientes_usuarios_id`)
    REFERENCES `db`.`clientes` (`id` , `usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arquivos_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `db`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
